const { lstatSync, readdirSync, copyFileSync, writeFileSync, mkdirSync } = require("fs");
const { dirname } = require("path");

const OUT_DIR = ".vercel/output";
const PROJECT_DIST = "dist/sap-store-6.x";

// This is the array of pages that are prerendered, specified in prerender-routes.txt
// Updates to these pages require a Vercel deployment
const SSG_PAGES = [
  {
    route: "/electronics-spa/en/USD/product/1934398/HDR-XR105E$",
    staticHTML: "/product/1934398/HDR-XR105E/index.html",
  }
]

// This is the array of pages that leverage Incremental Static Regeneration (ISR)
// The fallbackHTML is the path to the static HTML file that will be used for the initial render
// Subsequent renders will be generated by the ISR function and updated on a rolling interval (60 seconds)
const ISR_PAGES = [
  {
    id: "home",
    route: "/electronics-spa/en/USD/",
    fallbackHTML: "../static/index.html",
  },
  {
    id: "nv10",
    route: "/electronics-spa/en/USD/product/553637/NV10",
    fallbackHTML: "../static/product/553637/NV10/index.html",
  },
  {
    id: "dsc-n1",
    route: "/electronics-spa/en/USD/product/358639/DSC-N1",
    fallbackHTML: "../static/product/358639/DSC-N1/index.html",
  }
]

// Utility function for writing content to a file
function write(file, data) {
  try {
    mkdirSync(dirname(file), { recursive: true });
  } catch {}

  writeFileSync(file, data);
}

// Utility function for copying files from one directory to another
function copyFiles(source, target) {
  const files = readdirSync(source);
  for (const file of files) {
    const curSource = `${source}/${file}`;
    if (lstatSync(curSource).isDirectory()) {
      mkdirSync(`${target}/${file}`, { recursive: true });
      copyFiles(curSource, `${target}/${file}`);
    } else {
      copyFileSync(curSource, `${target}/${file}`);
    }
  }
}

// Utility function that will create the SSR function and copy all files to the Vercel output folder
function createSSRFunction() {
  const fn_dir = `${OUT_DIR}/functions/ssr.func`;
  write(
    `${fn_dir}/.vc-config.json`,
    JSON.stringify({
      runtime: "nodejs18.x",
      handler: "index.js",
      launcherType: "Nodejs",
    })
  );

  copyFiles(`${PROJECT_DIST}/server`, fn_dir);

  write(`${fn_dir}/index.js`, `module.exports = require("./main.js").app();`);

  // static files also need to be copied to the function dir because the server runtime uses them
  mkdirSync(`${fn_dir}/${PROJECT_DIST}/browser`, { recursive: true });
  copyFiles(`${PROJECT_DIST}/browser`, `${fn_dir}/${PROJECT_DIST}/browser`);
}

// Utility function that will create the ISR function and copy all files to the Vercel output folder
function createISRFunction(name, group, fallback) {
  const funcDir = `${OUT_DIR}/functions/${name}.func`;
  write(
    `${funcDir}/.vc-config.json`,
    JSON.stringify({
      runtime: "nodejs18.x",
      handler: "index.js",
      launcherType: "Nodejs",
    })
  );

  copyFiles(`${PROJECT_DIST}/server`, funcDir);

  write(`${funcDir}/index.js`, `module.exports = require("./main.js").app();`);

  // static files also need to be copied to the function dir because the server runtime uses them
  mkdirSync(`${funcDir}/${PROJECT_DIST}/browser`, { recursive: true });
  copyFiles(`${PROJECT_DIST}/browser`, `${funcDir}/${PROJECT_DIST}/browser`);

  // Create prerender config json file
  write(
    `${OUT_DIR}/functions/${name}.prerender-config.json`,
    JSON.stringify({
      // For this example, we are hardcoding the revalidation interval to 60 seconds
      expiration: 10,
      group,
      allowQuery: ["__pathname"],
      passQuery: true,
      fallback,
    })
  );
}

// Create the static Vercel folder
mkdirSync(`${OUT_DIR}/static`, { recursive: true });

// Copy the static files to the Vercel folder
copyFiles(`${PROJECT_DIST}/browser`, `${OUT_DIR}/static`);

// Create the SSR serverless function responsible for all pages that are not SSG or ISR
createSSRFunction();

// Create an ISR serverless function for each specified ISR page with specified fallback HTML
ISR_PAGES.forEach((page, i) => {
  createISRFunction(`isr-func-${page.id}`, ++i, page.fallbackHTML);
});

// Write the Vercel Build Output config file.
write(
  `${OUT_DIR}/config.json`,
  JSON.stringify({
    version: 12,
    routes: [
      ...SSG_PAGES.map(page => {
        return {
          src: `${page.route}$`,
          dest: page.staticHTML,
        }
      }),
      ...ISR_PAGES.map(page => {
        return {
          src: `${page.route}$`,
          dest: `/isr-func-${page.id}?__pathname=${page.route}`
        }
      }),
      // Specify that SSR should be used for all other pages
      { 
        src: "/.*", 
        dest: "/ssr" 
      },
    ],
  })
);
